#ifndef _FBXSDK_VERSION_H_
#define _FBXSDK_VERSION_H_
#define FBXSDK_VERSION_MAJOR 2017
#define FBXSDK_VERSION_MINOR 0
#define FBXSDK_VERSION_POINT 1
#define FBXSDK_VERSION_NAME  "Release"
#define FBXSDK_VERSION_YEAR     2016
#define FBXSDK_VERSION_MONTH 04
#define FBXSDK_VERSION_DAY  14
#ifndef FBXSDK_VERSION_REVISION
#define FBXSDK_VERSION_REVISION 0
#endif
#define FBX_STRING(x)  #x
#define FBX_STRINGIFY(x) FBX_STRING(x)
#if FBXSDK_VERSION_POINT == 0
#define FBXSDK_VER_TO_STR(a, b, c) FBX_STRING(a.b)
#else
#define FBXSDK_VER_TO_STR(a, b, c) FBX_STRING(a.b.c)
#endif
#define FBXSDK_VERSION_STRING  FBXSDK_VER_TO_STR(FBXSDK_VERSION_MAJOR, FBXSDK_VERSION_MINOR, FBXSDK_VERSION_POINT)
#define FBXSDK_VERSION_STRING_FULL FBXSDK_VERSION_STRING " " FBXSDK_VERSION_NAME " (" FBX_STRINGIFY(FBXSDK_VERSION_REVISION) ")"
#define FBXSDK_VERSION_DATE   FBX_STRINGIFY(FBXSDK_VERSION_YEAR) "" FBX_STRINGIFY(FBXSDK_VERSION_MONTH) "" FBX_STRINGIFY(FBXSDK_VERSION_DAY)
#ifndef FBXSDK_DEFINE_NAMESPACE
#define FBXSDK_DEFINE_NAMESPACE 1
#endif
#if FBXSDK_DEFINE_NAMESPACE == 1
#define FBXSDK_NAMESPACE fbxsdk
#else
#define FBXSDK_NAMESPACE
#endif
#endif